.\" This manpage is copyright (C) 2000, 2001, 2003, 2004 Progeny Linux
.\" Systems, Inc.
.\" Author: Branden Robinson <branden@progeny.com>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License with
.\" the Debian operating system, in /usr/share/common-licenses/GPL;  if
.\" not, write to the Free Software Foundation, Inc., 59 Temple Place,
.\" Suite 330, Boston, MA 02111-1307 USA
.\"
.\" We need the URL macro from groff's www macro package, but also want
.\" things to work all right for people who don't have it.  So we define
.\" our own URL macro and let the www macro package override it if it's
.\" available.
.de URL
\\$2 \(laURL: \\$1 \(ra\\$3
..
.if \n[.g] .mso www.tmac
.TH dexconf 1 "2004\-10\-31" "Debian Project"
.SH NAME
dexconf \- generate Xorg X server configuration file from debconf data
.SH SYNOPSIS
.B dexconf
[
.I options
]
.SH DESCRIPTION
.B dexconf
retrieves values from
.BR debconf (7)'s
database and uses them to build an
.I xorg.conf
file.
.PP
The information that
.B dexconf
uses is typically entered via a debconf frontend (or possibly in part by
hardware autodetection tools).
Note that
.B dexconf
itself does
.I not
set any values in the debconf database; it only retrieves them.
If configuration parameters of the debconf database need to be changed,
.BR dpkg\-reconfigure (8)
should be used to do so.
.PP
More experienced users should feel free to use
.BR dexconf \-generated
configuration files as a starting point for their customizations, since
individual preferences vary greatly.
.SH OPTIONS
.TP
.B \-h\fR,\fB \-\-help
Display a usage message and exit.
.TP
.BI \-o\  file \fR,\fB\ \-\-output= file
By default,
.B dexconf
writes to
.IR /etc/X11/xorg.conf
This option instructs
.B dexconf
to write to
.I file
instead.
Note that
.B dexconf
unconditionally overwrites its destination file if it has sufficient access
rights to do so.
.SH ENVIRONMENT
.TP
.B COLUMNS
This variable is used to format diagnostic messages so that they fit the
width of the terminal.
If not set, a terminal width of 80 columns is assumed.
.TP
.B TMPDIR
.B dexconf
creates a subdirectory of the directory name stored in this variable, and
uses that subdirectory as a scratch area.
If not set,
.I /tmp
is used as the parent of the scratch directory.
.SH "OUTPUT FILES"
.TP
.I /etc/X11/xorg.conf
is the configuration file for the Xorg X server.
.SH DIAGNOSTICS
.B dexconf
produces diagnostic messages upon encountering various error conditions.
These messages are prefixed with the name of the command and a colon; for
example:
.RS
.BI "dexconf: " message
.RE
A list of diagnostic messages currently issued by
.B dexconf
follows.
.TP
.B This option, and XFree86 3.x output, are no longer supported.
.B dexconf
no longer supports the
.BR \-f ,
.B \-\-format
option.
See the \(lqHISTORY\(rq section below.
.TP
.BI "cannot create temporary work directory; " dirname " does not exist or is\
\& not a directory"
.B
dexconf
was unable to create a scratch directory to work in because the parent
directory
.RI ( dirname )
was not does not exist or is not a directory.
Create
.I dirname
and set its permissions properly, or set the
.B TMPDIR
environment variable to the name of an existing directory.
.TP
.BI "cannot create temporary work directory in " dirname "; directory not\
\& writable"
.B dexconf
had insufficient permissions to create a directory in
.IR dirname .
Change the permissions on
.I dirname
or set the
.B TMPDIR
environment variable to the of a writeable directory.
.TP
.BI "cannot generate configuration file; " question " not set"
An answer to the indicated
.I question
was expected in the debconf database, but none was found.
.B dexconf
cannot write a valid configuration file without this information.
This problem can be rectified by reconfiguring the X server package with
the
.BR dpkg\-reconfigure (8)
command.
.TP
.BI "creation of temporary work directory " dirname " failed"
.B dexconf
was unable to create a scratch directory
.RI ( dirname )
to work in.
This diagnostic is only issued after
.B dexconf
has checked to ensure that the parent directory of
.I dirname
is writable, and after the temporary directory to be used has been removed
(if necessary).
This diagnostic message could indicate that something on the system is
attempting to use a temporary\-file race condition to compromise the
system's integrity.
.TP
.B error while getting options
.B dexconf
received an error from
.BR getopt (1)
while attempting to interpret the command\-line arguments.
Use only the documented options.
.TP
.B received signal; aborting
.B dexconf
was sent a fatal signal; see the section on asynchronous events below.
.TP
.BI "this program does not know how to configure the " package " X server"
.B dexconf
only knows how to write configuration files for XFree86 version
.RI 4. x
X servers.
The value of the
.B shared/default\-x\-server
debconf template was set to a package name that
.B dexconf
did not recognize.
A different tool will have to be used to configure the
selected X server, or
.BR dpkg\-reconfigure (8)
will have to be used to change the default X server.
.TP
.BI "unable to write to " configfile
.B dexconf
was unable to write to
.I configfile
because it lacked permissions to do so.
Run
.B dexconf
as a user with permissions to write to
.IR configfile,
or specify an alternate file to write with the
.B \-o
or
.B \-\-output
options.
.TP
.BI "unrecognized option " "option"
An unrecognized option was specified.
Use only the documented options.
.SH "ASYNCHRONOUS EVENTS"
.B dexconf
traps the HUP, INT, QUIT, and TERM signals.
.B dexconf
removes its scratch directory and exits when it receives any of these
signals.
.SH "EXIT STATUS"
.TP
0
A configuration file was successfully written.
.TP
1
An error occurred, or
.B dexconf
was interrupted.
See the section on diagnostics above.
.SH BUGS
See
.URL "http://bugs.debian.org/xserver\-common" "the Debian Bug Tracking System" .
If you wish to report a bug in
.BR dexconf ,
please see
.I /usr/share/doc/debian/bug\-reporting.txt
or the
.BR reportbug (1)
command.
.SH AUTHOR
.B dexconf
was written by Branden Robinson with sponsorship from Progeny Linux Systems.
.SH "SEE ALSO"
.BR xorg.conf (5x),
.BR dpkg\-reconfigure (8),
.BR debconf (7)
.\" vim:set et tw=80:
